# Generated by Django 4.1.5 on 2023-04-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
        ('api', '0002_auto_20201218_1626'),
    ]

    operations = [
    ]
